modLoader="lowcodefml"
loaderVersion="*"
issueTrackerURL="https://github.com/QikaHome/Tinkers-Waste/issues"
license="MIT"
[[mods]]
    modId="tinkers_waste"
    version="0.0.2"
    displayName="Tinkers' Useful Items"
    description='''
    An add-on for Tinkers' Construct that is not wasteful at all
    '''
[[dependencies.tinkers_things]]
    modId="tconstruct"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_things]]
    modId="jsonthings"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="BOTH"
